# Generated by Django 3.2.2 on 2021-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210527_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('name', 'number')},
        ),
    ]
