# Generated by Django 3.2.2 on 2021-05-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210528_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={},
        ),
    ]
