# Generated by Django 3.2.2 on 2021-05-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hardware_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
