# Generated by Django 3.2.2 on 2021-05-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hardware_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='invent_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
