# Generated by Django 3.2.2 on 2021-05-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_hardware_invent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Группа оборудования')),
            ],
        ),
        migrations.AlterField(
            model_name='type_hardware',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='type_hardware',
            name='group_hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group_hardware'),
        ),
    ]
