# Generated by Django 3.2.2 on 2021-05-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210528_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_hardware',
            options={'verbose_name': 'Группа оборудования', 'verbose_name_plural': 'Группы оборудования'},
        ),
        migrations.AddField(
            model_name='hardware',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group_hardware'),
        ),
    ]
