# Generated by Django 3.2.2 on 2021-06-19 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210602_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип комплектующей')),
            ],
            options={
                'verbose_name': 'Тип комплектующей',
                'verbose_name_plural': 'Типы комплектующих',
            },
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Date_purchase',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='model',
            field=models.CharField(max_length=200, null=True, verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('name_of_component', models.CharField(max_length=200, verbose_name='Название комплектующей')),
                ('Purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('Warranty_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата конца гарантии')),
                ('Hardware_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hardware')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.components_type')),
            ],
        ),
    ]
