# Generated by Django 3.2.2 on 2021-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210619_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'verbose_name': 'Комплектующая', 'verbose_name_plural': 'Комплектующие'},
        ),
        migrations.AddField(
            model_name='components',
            name='specifications_components',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики комлектующей'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='specifications_hardware',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики оборудования'),
        ),
    ]
