# Generated by Django 3.2.2 on 2021-06-22 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210619_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='Hardware_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hardware', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='components',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='components',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.components_type', verbose_name='Тип комплектующей'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Date_end_warranty',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата конца гарантии'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Date_purchase',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала эклуатации'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group_hardware', verbose_name='Группа оборудования'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.statuses', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.type_hardware', verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departments', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='type_hardware',
            name='group_hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group_hardware', verbose_name='Группа оборудования'),
        ),
        migrations.CreateModel(
            name='Operation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сhange_date', models.DateTimeField(default=datetime.datetime.now)),
                ('operation', models.CharField(max_length=200, verbose_name='Операция')),
                ('worker', models.CharField(max_length=200, verbose_name='Работник')),
                ('wogfrker', models.CharField(blank=True, max_length=200, null=True, verbose_name='Работник')),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hardware', verbose_name='Оборудование')),
                ('сomponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.components', verbose_name='Комплектующая')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'История операций',
            },
        ),
    ]
