# Generated by Django 3.2.2 on 2021-06-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210622_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_history',
            name='wogfrker',
        ),
    ]
