# Generated by Django 3.2.2 on 2021-06-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_operation_history_wogfrker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='E-mail'),
        ),
    ]
