# Generated by Django 3.2.2 on 2021-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_history',
            name='hard_type',
            field=models.CharField(default='Пока не добавлени тип', max_length=200, verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
    ]
