# Generated by Django 3.2.2 on 2021-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_operation_history_hard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
