# Generated by Django 3.2.2 on 2021-06-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_staff_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_history',
            name='hardware',
            field=models.CharField(max_length=200, null=True, verbose_name='Оборудование'),
        ),
    ]
