# Generated by Django 3.2.2 on 2021-06-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_operation_history_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_history',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.statuses', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
