# Generated by Django 3.2.2 on 2021-06-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_operation_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_history',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.statuses', verbose_name='Статус'),
        ),
    ]
