# Generated by Django 3.2.2 on 2021-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_operation_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_history',
            name='сomponent',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комплектующая'),
        ),
    ]
